### ISSUE TITLE
Typecast issue exists in scalardb with cosmos db. 

### ISSUE THREAD

**Issue by scalar-boney** [scalar-labs/scalardb#89] opened 2020-10-10 07:27 UTC
**Describe the bug**
Typecast issue exists in scalardb while reading data from Cosmos DB using scalardb

**To Reproduce**
1. Setup [QA application with cosmos db](https://github.com/scalar-labs/getting-started-with-scalardb)
2. Login to QA application
3. Insert some questions using the `Submit a Question` button. 
4. See some error `An error occurred while looking up the question` after creating the question.

**Expected behavior**
Read data from cosmos db using scalardb without any error.

**Screenshots**
Typecast issue exists while reading data from cosmos db.

**Backend Details**
 - Scalardb: 2.2.0
 - Storage: Cosmos DB

**Additional context**
Issue related logs
```
2020-10-08 23:12:59.355 ERROR 8243 --- [0.1-8090-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long] with root cause

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
        at com.scalar.db.storage.cosmos.ResultImpl.convert(ResultImpl.java:142) ~[scalardb-2.2.0.jar:na]
        at com.scalar.db.storage.cosmos.ResultImpl.add(ResultImpl.java:120) ~[scalardb-2.2.0.jar:na]
        at com.scalar.db.storage.cosmos.ResultImpl.lambda$interpret$0(ResultImpl.java:101) ~[scalardb-2.2.0.jar:na]
        at com.google.common.collect.ImmutableSortedMap.forEach(ImmutableSortedMap.java:588) ~[guava-24.1-jre.jar:na]
        at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1505) ~[na:1.8.0_152-ea]
        at com.scalar.db.storage.cosmos.ResultImpl.interpret(ResultImpl.java:99) ~[scalardb-2.2.0.jar:na]
        at com.scalar.db.storage.cosmos.ResultImpl.<init>(ResultImpl.java:44) ~[scalardb-2.2.0.jar:na]
        at com.scalar.db.storage.cosmos.ScannerIterator.next(ScannerIterator.java:34) ~[scalardb-2.2.0.jar:na]
        at com.scalar.db.storage.cosmos.ScannerIterator.next(ScannerIterator.java:9) ~[scalardb-2.2.0.jar:na]
        at com.example.qa.dao.question.QuestionDao.scan(QuestionDao.java:49) ~[main/:na]
        at com.example.qa.service.question.QuestionServiceForStorage.get(QuestionServiceForStorage.java:130) ~[main/:na]
        at com.example.qa.controller.question.QuestionController.getQuestions(QuestionController.java:54) ~[main/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_152-ea]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_152-ea]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_152-ea]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_152-ea]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) ~[spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877) ~[spring-webmvc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783) ~[spring-webmvc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
```

**Comment by yito88** [comment] 2020-10-12 01:35
Thank you for the reporting.
I'd like to know if a non-zero value of the attribute works well.

Could you change the initial value `0L` of the `updatedAt` attribute and try again?
I think it's OK to use `millis` of the `createdAt` attribute for the value.
https://github.com/scalar-labs/getting-started-with-scalardb/blob/db5c8aa93c41f57e5e2a82c679e8ff6c4dfc2b53/backend/QA/src/main/java/com/example/qa/service/question/QuestionServiceForStorage.java#L57

In my test, an attribute with the long type can be read.
I guess that some values like zero are converted to integer values on Cosmos DB.

I think we have to fix this cast even if it would work well.

**Comment by yito88** [comment] 2020-10-13 05:42
I could reproduce this issue with simple operations.

I created a table that has a `bigint` attribute and inserted a record that has zero for the attribute.
Then, I read the value and got `ClassCastException`.
With PR #96, it worked well without the exception.

**Comment by scalar-boney** [comment] 2020-10-23 04:10
> Could you change the initial value 0L of the updatedAt attribute and try again?

It is working fine after updating the value of `updatedAt` from `0L` to `millis` on `QuestionServiceForStorage.java` .

https://github.com/scalar-labs/getting-started-with-scalardb/blob/db5c8aa93c41f57e5e2a82c679e8ff6c4dfc2b53/backend/QA/src/main/java/com/example/qa/service/question/QuestionServiceForStorage.java#L57

**Comment by feeblefakie** [comment] 2021-01-26 06:25
Closing it since it is resolved.

**Closed by feeblefakie** 2021-01-26 06:25 UTC
